### ISSUE TITLE
Typo: Fix susbtrate -> substrate

### ISSUE THREAD

**Issue by a-jwc** [bit-country/bit.country-website#1]
![image](https://user-images.githubusercontent.com/68071075/135184327-8d576460-85ce-4cb4-a7ed-c17f2a265647.png)

**Comment by bit2world** [comment]
Can I contribute on this?

**Comment by codemeit** [comment]
Thanks for pointing it out.

**Comment by bit2world** [comment]
How can I contribute on this project as Frontend Engineer?

**Comment by codemeit** [comment]
Thanks for your interest. Feel free to send your CV hi@bit.country
